Work around an rpath problem on macOS.
I think this is a CMake bug - if hypre and PETSc are installed in the same place
then CMake puts calls like

    execute_process(COMMAND /usr/bin/install_name_tool
      -delete_rpath "/Users/drwells/autoibamr/packages/petsc-3.13.1/lib"
      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libIBAMR2d.dylib")

inside src/cmake_install.cmake. This doesn't make any sense: that path doesn't
need to be removed from the library prior to installation because it is for an
external dependency. Furthermore, those paths are duplicated, which leads to
errors of the form

error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: for: /Users/drwells/autoibamr/packages/IBAMR-0.10.0-rc1/lib/libIBAMR3d.dylib (for architecture x86_64) option "-add_rpath /Users/drwells/autoibamr/packages/petsc-3.13.1/lib" would duplicate path, file already has LC_RPATH for: /Users/drwells/autoibamr/packages/petsc-3.13.1/lib

which cause installation to fail.

We can work around this by relying on PETSc to transitively link to hypre for us
in this case.