Fix C++11 static constexpr ODR-usage errors
Add out-of-class definitions for static constexpr members to fix
potential linker errors in C++11. When static constexpr members are
ODR-used (One Definition Rule), they require out-of-class definitions
even though they have in-class initializers.

Fixes applied to:
- IBEELKinematicsZhang.cpp: 5 constants (ZHANG_A_MAX, ZHANG_ENVELOPE_C0, etc.)
- AnalyticalSolutions.cpp: 2 constants (PI, EPSILON)
- TestUtilities.cpp: 3 constants (LINE_WIDTH, SEPARATOR_CHAR, SUBSEPARATOR_CHAR)

This prevents linker errors such as:
  undefined reference to 'IBAMR::IBEELKinematicsZhang::ZHANG_A_MAX'
  undefined reference to 'TestUtilities::AnalyticalSolutions::PI'

Note: In C++17, this is no longer required due to inline variables,
but IBAMR uses C++11/C++14 standards.